### ISSUE TITLE
[ABI] need to refactor dynamic values for multiple returns

### ISSUE THREAD

**Issue by VoR0220** [eris-ltd/eris-abi#20]
Currently the ABI handles multiple types strangely from the solidity compiler perspective. This needs refactoring.

**Comment by compleatang** [comment]
related to https://github.com/eris-ltd/eris-pm/issues/112

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1002](https://github.com/eris-ltd/eris-cli/issues/1002) via [**ZenHub**](https://www.zenhub.com/)
